core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('generate_docx.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

generate_docx/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'input'

urlpatterns = [
    path('', views.start_page, name='start_page'),
    path('input/<int:id_>/', views.create_documents, name='detail_page'),
    path('create_client/', views.create_client, name='create_client'),
    path('register/', views.register, name='register'),
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('send/', views.send_mail, name='send_mail'),
    path('download/', views.download_file, name='download_file'),
    path('screenshot/', views.screenshot, name='screenshot'),

]

templates/base.html
{% load bootstrap4 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MY DEFAULT TITLE{% endblock %}</title>
    <link href="{% static 'styles.css' %}" rel="stylesheet">
</head>
<body>
{% block menu %}
<div class="fixed-top d-flex flex-column flex-md-row align-items-center px-md-4 bd-black border-bottom shadow-sm">
    <a class="text-dark m-1 my-0 mr-md-auto font-weight-normal" href="{% url 'input:start_page' %}">Акты</a>
{#  <h5 class="my-0 mr-md-auto font-weight-normal">Хорошее приложение</h5>#}
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="text-dark m-1" href="{% url 'input:start_page' %}">Главная</a>
<!--    <a class="text-dark m-1" href="#">Обучение</a>-->
<!--    <a class="text-dark m-1" href="#">О проекте</a>-->
    {% if request.user.is_authenticated %}
<!--        <a class="text-dark m-1" href="{% url 'input:start_page' %}">Профиль</a>-->
        <a class="text-dark m-1" href="{% url 'input:logout' %}">Выйти</a>
    {% else %}
        <a class="btn btn-outline-dark p-1 m-1" href="{% url 'input:login' %}">Вход</a>
<!--        <a class="btn btn-outline-dark p-1" href="{% url 'input:register' %}">Регистрация</a><br>-->
    {% endif %}
  </nav>
</div><br>
{% endblock %}
{% block content %}
{% endblock %}
</body>
</html>

templates/create_client.html
{% extends "base.html" %}

{% block content %}
<br><br>
 <div class="container container-register">
    <div class="row">
        <div class="col-12" style="padding-left: 30%; padding-right: 30%;">
            <h3 class="text-center">Заполнение реквизитов клиента</h3>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="col-xs-12">
                    <div class="form-group">
                         <p><label for='{{ form.number_of_contract }}'></label>
                            <input type="text" class="form-control" placeholder="Номер договора" name="number_of_contract" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.date_of_contract }}'></label>
                            <input type="text" class="form-control" placeholder="Дата заключения договора" name="date_of_contract" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.city }}'></label>
                            <input type="text" class="form-control" placeholder="Город" name="city" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.name_of_organization }}'></label>
                            <input class="form-control" placeholder="Наименование организации" name="name_of_organization" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.in_face }}'></label>
                            <input type="text" class="form-control" placeholder="В лице(Директора)" name="in_face" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.in_face_in_nominative }}'></label>
                            <input type="text" class="form-control" placeholder="В лице в именительном падеже(Директор)" name="in_face_in_nominative" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.name_face_organizations }}'></label>
                            <input type="text" class="form-control" placeholder="ФИО представителя организации" name="name_face_organizations" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.acting_on_the_basis }}'></label>
                            <input type="text" class="form-control" placeholder="На основании(Устава)" name="acting_on_the_basis" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.legal_address }}'></label>
                            <input class="form-control" placeholder="Юридический адрес" name="legal_address" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.address_of_bank }}'></label>
                            <input class="form-control" placeholder="Банковские реквизиты" name="address_of_bank" required autocomplete="off" /></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.unp }}'></label>
                            <input type="text" class="form-control" placeholder="УНП" name="unp" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.initials }}'></label>
                            <input type="text" class="form-control" placeholder="Инициалы(И.И.Иванович)" name="initials" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.phone_number }}'></label>
                            <input type="text" class="form-control" placeholder="Номер телефона" name="phone_number" autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.email }}'></label>
                            <input type="email" class="form-control" placeholder="Email" name="initials" autocomplete="off"/></p>
                    </div>
                </div>
                <div class="text-center col-xs-12">
                    <input type="submit" class="btn btn-lg btn-warning btn-block" value="Добавить клиента" />
                </div>
            </form>
        </div>
    </div>
 </div>
<!--<form action="" method="POST">-->
<!--    {% csrf_token %}-->
<!--    {{ create_form }}-->
<!--    <input type="submit" value="Submit">-->
<!--</form>-->
{% endblock %}

templates/detail.html
{% extends "base.html" %}

{% block content %}
<!--<form action="" method="POST">-->
<!--    {% csrf_token %}-->
<!--    {{ form }}-->
<!--    <input type="submit" value="Submit">-->
<!--</form>-->
<br><br>
 <div class="container container-register">
    <div class="row">
        <div class="col-12" style="padding-left: 30%; padding-right: 30%;">
            <h3 class="text-center">Генерация акта</h3>
            <form action="." method="post"  style="margin-top:20px">
                {% csrf_token %}
                <div class="col-xs-12">
                    <div class="form-group">
                         <p><label for='{{ form.number_document }}'></label>
                            <input type="text" class="form-control" placeholder="Номер акта" name="number_document" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.data_creation }}'></label>
                            <input type="text" class="form-control" placeholder="Дата заключения акта" name="data_creation" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.name_of_work }}'></label>
                            <input type="text" class="form-control" placeholder="Наименование работ" name="name_of_work" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.count_hours }}'></label>
                            <input type="text" class="form-control" placeholder="Количество часов" name="count_hours" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.cost }}'></label>
                            <input type="text" class="form-control" placeholder="Стоимость работ" name="cost" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.name_of_document }}'></label>
                            <input type="text" class="form-control" placeholder="Наименование документа" name="name_of_document" autocomplete="off"/></p>
                    </div>
                </div>
                <div class="text-center col-xs-12">
                    <input type="submit" class="btn btn-lg btn-warning btn-block" value="Отправить акт" />
                </div>
            </form>
        </div>
    </div>
 </div>
{% endblock %}

templates/docx.html
{% extends "base.html" %}
{% block content %}
<br><br>
<div class="container">
    <div class="row">
        <div class="col">
            <h3 style="width: 650px;margin-left: 20px;text-align: center;">Предварительный просмотр</h3>
                <p style="text-align: center;"><a style="margin-left: 20px;" href="{% url 'input:send_mail' %}" class="btn btn-lg btn-warning">Отправить на почту</a>
                    <a style="margin-left: 20px;" href="{% url 'input:download_file' %}" class="btn btn-lg btn-warning">Скачать</a></p>
            {% if name_of_document %}
                <iframe
                src="http://docs.google.com/gview?url=http://45.84.226.60:8000/static/{{ name_of_document }}.docx&embedded=true"
                style="width:650px; height:750px;"
                ></iframe>
            {% else %}
                <iframe
                src="http://docs.google.com/gview?url=http://45.84.226.60:8000/static/{{data}}-Act-{{number}}.docx&embedded=true"
                style="width:650px; height:750px;"
                ></iframe>
            {% endif %}
        </div>
        <div class="col">
            <h3 class="text-center">Редактирование акта</h3>
            <form action="." method="post"  style="margin-top:20px">
                {% csrf_token %}
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.number_document }}'></label>
                        <input type="text" class="form-control" value="{{form.number_document.value}}" placeholder="Номер акта" name="number_document" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.data_creation }}'></label>
                        <input type="text" class="form-control" value="{{form.data_creation.value}}" placeholder="Дата заключения акта" name="data_creation" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.name_of_work }}'></label>
                        <input type="text" class="form-control" value="{{form.name_of_work.value}}" placeholder="Наименование работ" name="name_of_work" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.count_hours }}'></label>
                        <input type="text" class="form-control" value="{{form.count_hours.value}}" placeholder="Количество часов" name="count_hours" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.cost }}'></label>
                        <input type="text" class="form-control" value="{{form.cost.value}}" placeholder="Стоимость работ" name="cost" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.name_of_document }}'></label>
                            <input type="text" class="form-control" value="{{form.name_of_document.value}}" placeholder="Наименование документа" name="name_of_document" autocomplete="off"/></p>
                    </div>
                </div>
                <div class="text-center col-xs-12">
                    <input type="submit" class="btn btn-lg btn-warning btn-block" value="Изменить" />
                </div>
            </form>
        </div>
    </div>
</div>

<!--<br><br>-->
<!--&lt;!&ndash;{{file|safe}}&ndash;&gt;-->
<!-- <div class="container container-register">-->
<!--    <div class="row">-->
<!--        <div class="col-12" style="padding-left: 20%;">-->
<!--            <h3 style="width: 650px;margin-left: 20px;">Предварительный просмотр<a style="margin-left: 20px;" href="{% url 'input:send_mail' %}" class="btn btn-lg btn-warning">Отправить на почту</a></h3>-->
<!--            <iframe-->
<!--            src="http://docs.google.com/gview?url=http://45.84.226.60:8000/static/{{data}}-Act-{{number}}.docx&embedded=true"-->
<!--            style="width:650px; height:750px;"-->
<!--            ></iframe>-->
<!--            <br>-->
<!--        </div>-->
<!--    </div>-->
<!-- </div>-->
<!--<br><br>-->
<!-- <div class="container container-register">-->
<!--    <div class="row">-->
<!--        <div class="col-12" style="padding-left: 30%; padding-right: 30%;">-->
<!--            <h3 class="text-center">Генерация акта</h3>-->
<!--            <form action="." method="post"  style="margin-top:20px">-->
<!--                {% csrf_token %}-->
<!--                <div class="col-xs-12">-->
<!--                    <div class="form-group">-->
<!--                         <p><label for='{{ form.number_document }}'></label>-->
<!--                            <input type="text" class="form-control" value="{{form.number_document.value}}" placeholder="Номер акта" name="number_document" required autocomplete="off"/></p>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col-xs-12">-->
<!--                    <div class="form-group">-->
<!--                        <p><label for='{{ form.data_creation }}'></label>-->
<!--                            <input type="text" class="form-control" value="{{form.data_creation.value}}" placeholder="Дата заключения акта" name="data_creation" required autocomplete="off"/></p>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col-xs-12">-->
<!--                    <div class="form-group">-->
<!--                        <p><label for='{{ form.name_of_work }}'></label>-->
<!--                            <input type="text" class="form-control" value="{{form.name_of_work.value}}" placeholder="Наименование работ" name="name_of_work" required autocomplete="off"/></p>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col-xs-12">-->
<!--                    <div class="form-group">-->
<!--                        <p><label for='{{ form.count_hours }}'></label>-->
<!--                            <input type="text" class="form-control" value="{{form.count_hours.value}}" placeholder="Количество часов" name="count_hours" required autocomplete="off"/></p>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col-xs-12">-->
<!--                    <div class="form-group">-->
<!--                        <p><label for='{{ form.cost }}'></label>-->
<!--                            <input type="text" class="form-control" value="{{form.cost.value}}" placeholder="Стоимость работ" name="cost" required autocomplete="off"/></p>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="text-center col-xs-12">-->
<!--                    <input type="submit" class="btn btn-lg btn-warning btn-block" value="Изменить" />-->
<!--                </div>-->
<!--            </form>-->
<!--        </div>-->
<!--    </div>-->
<!-- </div>-->
{% endblock %}

templates/get_photo.html
{% extends "base.html" %}

{% block title %}Registration confirmation{% endblock %}

{% block content %}
<br><br>
<div class="container">
    <div class="row">
        <div class="col">
            <h3 style="width: 650px;margin-left: 20px;text-align: center;">Предварительный просмотр скриншота</h3>
<!--                <p style="text-align: center;"><a style="margin-left: 20px;" href="{% url 'input:send_mail' %}" class="btn btn-lg btn-warning">Отправить на почту</a>-->
<!--                    <a style="margin-left: 20px;" href="{% url 'input:download_file' %}" class="btn btn-lg btn-warning">Скачать</a></p>-->
<!--                <img src="static 'screenshot/.png'" alt="альтернативный текст">-->
            <iframe
                src="http://docs.google.com/gview?url=http://45.84.226.60:8000/static/{{ name_of_photo }}.png&embedded=true"
                style="width:650px; height:750px;"
                ></iframe>

        </div>
    </div>
</div>
{% endblock %}

templates/input.html
{% extends "base.html" %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

templates/link.html
{% extends "base.html" %}

{% block title %}Registration confirmation{% endblock %}
{% block content %}
<br><br>
 <div class="container container-register">
    <div class="row">
        <div class="col-12" style="padding-left: 30%; padding-right: 30%;">
            <h3 class="text-center">Screenshot<h3>
            <form action="." method="post"  style="margin-top:20px">
                {% csrf_token %}
                <div class="col-xs-12">
                    <div class="form-group">
                         <p><label for='{{ form.link }}'></label>
                            <input type="text" class="form-control" placeholder="Cсылка на страницу" name="link" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                         <p><label for='{{ form.name_of_photo }}'></label>
                            <input type="text" class="form-control" placeholder="Название скриншота" name="name_of_photo" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="text-center col-xs-12">
                    <input type="submit" class="btn btn-lg btn-warning btn-block" value="Получить скриншот" />
                </div>
            </form>
        </div>
    </div>
 </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}
{% block content %}
<br><br>
 <div class="container container-register">
    <div class="row">
        <div class="col-12" style="padding-left: 30%; padding-right: 30%;">
            <h3 class="text-center">Регистрация</h3>
            <form action="." method="post"  style="margin-top:20px">
                {% csrf_token %}
                {{ user_form.errors }}
                <div class="col-xs-12">
                    <div class="form-group">
                         <p><label for='{{ user_form.username }}'></label>
                            <input type="text" class="form-control" placeholder="Введите логин" name="username" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ user_form.email }}'></label>
                            <input type="email" class="form-control" placeholder="Введите email" name="email" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ user_form.password }}'></label>
                            <input type="password" class="form-control" placeholder="Введите пароль" name="password" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ user_form.password2 }}'></label>
                            <input type="password" class="form-control" placeholder="Повторите пароль" name="password2" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="text-center col-xs-12">
                    <input type="submit" class="btn btn-lg btn-warning btn-block" value="Зарегистрироваться" />
                </div>
            </form>
        </div>
    </div>
 </div>
{% endblock %}

templates/register_done.html
{% extends "base.html" %}

{% block title %}Registration confirmation{% endblock %}
{% block content %}
    <br>
    <div class="container">
        <div class="row justify-content-center">
            <div class="text-center col-12 mr-1">
                <h3 >Здравствуйте {{ new_user.username }}! Вы зарегистрировались. Войдите в систему:</h3>
            </div><br>
            <div class="text-center col-xs-12 mr-1">
                <a class="btn btn-lg btn-warning btn-block" href="{% url 'input:login' %}">Войти</a>
            </div>
            <div class="text-center col-xs-12">
                <a class="btn btn-lg btn-warning btn-block" href="{% url 'input:start_page' %}">Вернуться на главную</a>
            </div>
        </div>
    </div>

{% endblock %}

templates/send.html
{% extends "base.html" %}

{% block content %}
<br><br>
 <div class="container container-register">
    <div class="row">
        <div class="col-12" style="padding-left: 30%; padding-right: 30%;">
            <h3 class="text-center">Данные для отправки письма</h3>
            <form action="." method="post"  style="margin-top:20px">
                {% csrf_token %}
                <div class="col-xs-12">
                    <div class="form-group">
                         <p><label for='{{ form.topic }}'></label>
                            <input type="text" class="form-control" placeholder="Тема письма" name="topic" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.text }}'></label>
                            <input type="text" class="form-control" placeholder="Текст письма" name="text" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ form.email }}'></label>
                            <input type="text" class="form-control" placeholder="Почта" name="email" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="text-center col-xs-12">
                    <input type="submit" class="btn btn-lg btn-warning btn-block" value="Отправить акт" />
                </div>
            </form>
        </div>
    </div>
 </div>
{% endblock %}

templates/send_done.html
{% extends "base.html" %}

{% block title %}Registration confirmation{% endblock %}
{% block content %}
    <br>
    <div class="container">
        <div class="row justify-content-center">
            <div class="text-center col-12 mr-1">
                <h3 >Сообщение успешно отправлено!</h3>
            </div><br>
            <div class="text-center col-xs-12">
                <a class="btn btn-lg btn-warning btn-block" href="{% url 'input:start_page' %}">Вернуться на главную</a>
            </div>
        </div>
    </div>

{% endblock %}

templates/start_page.html
{% extends "base.html" %}

{% block content %}
<!-- <div class="container container-register">-->
<!--    <div class="row">-->
<!--        <div class="col-12">-->
<!--            <br>-->
<!--            <h3>Список клиентов<a href="{% url 'input:create_client' %}" class="btn btn-lg btn-warning">Добавить клиента</a></h3>-->
<!--            {% for client in clients %}-->
<!--            <div class="row">-->
<!--              <div class="col-sm-6">-->
<!--                <div class="card">-->
<!--                  <div class="card-body">-->
<!--                    <h5 class="card-title">{{ client.name_of_organization }}</h5>-->
<!--                    <p class="card-text">Дата заключения договора: {{ client.date_of_contract }}</p>-->
<!--                    <a href="{{ client.get_absolute_url }}" class="btn btn-lg btn-warning btn-block">Подготовить акт</a>-->
<!--                  </div>-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--    </div>-->
<!-- </div>-->
<br><br>
 <div class="container container-register">
    <div class="row">
        <div class="col-12" style="padding-left: 30%; padding-right: 30%;">
            <h3>Список клиентов<a href="{% url 'input:create_client' %}" class="btn btn-lg btn-warning">Добавить клиента</a></h3>
            {% for client in clients %}
            <div class="row">
              <div class="col-sm-12">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">{{ client.name_of_organization }}</h5>
                    <p class="card-text">Дата заключения договора: {{ client.date_of_contract }}</p>
                    <a href="{{ client.get_absolute_url }}" class="btn btn-lg btn-warning btn-block">Подготовить акт</a>
                  </div>
                </div>
              </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </div>
 </div>
{% endblock %}